# Report-specific parameters
template: patientProfilesTemplate.Rmd
templatePackage: medicalMonitoring
reportTitle: Patient profiles
reportTitleLevel: 1
createPatientProfiles: TRUE

# Parameters used for all modules
patientProfilesGeneralParams:
# only create patient profiles for the subjects part of the safety population
  subsetDataFileName: adsl.sas7bdat
  subsetVar: SAFFL
  subsetValue: 'Y'

# Parameters for the creation of each specific module
patientProfilesParams:

  - typePlot: text
    dataFileName: adsl.xpt
    plotParams:
      paramValueVar: ["SEX", "RACE", "ETHNIC", "SITEID", "AGE", "TRTSDT", "ARM"]
      title: Demography
      label: DM
              
  - typePlot: text
    dataFileName: adae.xpt
    plotParams:
      paramValueVar: ["AEDECOD", "AESER" ,"AESEV", "AEREL", "ASTDY", "AENDY"]
      table: true
      title: Adverse events listing
      label: AEtext
      
  - typePlot: interval
    dataFileName: adae.xpt
    dataProcessing:
      - annotate:
        - vars: AESEVN
          varFct: "as.numeric(as.factor(AESEV))"
        - vars: AESEV
          varFct: "reorder(AESEV, AESEVN)"
    plotParams:
      paramVar: AEDECOD
      timeStartVar: ASTDY
      timeEndVar: AENDY
 #     timeStartShapeVar: ASTFLG
 #     timeEndShapeVar: AENFLG
      colorVar: AESEV
      shapePalette:
        Complete: "\u25A0"
        Partial: "\u25CB"
        Missing start: "\u25C4"
        Missing end: "\u25BA"
        Ongoing: "\u25BA"
        'NA': "+"
      shapeLab: Date status
      shapeSize: 4
      alpha: 0.6
      title: Adverse events graph
      label: AE
      
#  - typePlot: interval
#    dataFileName: adcm.xpt
#    plotParams:
#      paramVar: [CMDECOD]
#      paramGroupVar: CMCLAS
#      timeStartVar: ASTDY
#      timeEndVar: AENDY
 #     timeStartShapeVar: ASTFLG
 #     timeEndShapeVar: AENFLG
#      colorVar: ACMATC1T
#      timeTrans: 'getTimeTrans(type = "asinh-neg")'
#      timeExpand: "expansion(mult = 0.01)"
#      shapePalette:
#        Complete: "\u25A0"
#        Partial: "\u25CB"
#        Missing start: "\u25C4"
#        Missing end: "\u25BA"
#        Ongoing: "\u25BA"
#        'NA': "+"
#      shapeLab: Date status
#      shapeSize: 4
#      timeAlign: false
#      alpha: 0.6
#      title: Concomitant medications
#      label: CM

  - typePlot: line
    dataFileName: adlbc.xpt
    dataProcessing:
      - annotate:
        - vars: LBNRIND
          varFct: 'factor(LBNRIND)'
    plotParams:
      paramValueVar: AVAL
      paramValueRangeVar: [A1LO, A1HI]
      paramNameVar: [PARAM]
      paramGroupVar: [PARCAT1]
      timeVar: ADY
      colorVar: LBNRIND
      shapeVar: LBNRIND
      shapePalette: 
        Low Panic: "\u25BC"
        Low: "\u25BC"
        Low Normal: "\u25BC"
        Normal: "\u25CF"
        High Normal: "\u25B2"
        High: "\u25B2"
        High Panic: "\u25B2"
        Abnormal: "\u2666"
        Unknown: "+"
        'NA': "+"
      shapeSize: 4
      alpha: 0.6
      title: Laboratory test measurements
      label: LB

  - typePlot: line
    dataFileName: advs.xpt
    dataProcessing:
      - annotate:
        - vars: ANRIND
          varFct: 'factor(ANRIND)'
    plotParams:
      paramValueVar: AVAL
      paramValueRangeVar: [ANRLO, ANRHI]
      paramNameVar: [PARAM]
      timeVar: ADY
      colorVar: ANRIND
      shapeVar: ANRIND
      shapePalette: 
        Low Panic: "\u25BC"
        Low: "\u25BC"
        Low Normal: "\u25BC"
        Normal: "\u25CF"
        High Normal: "\u25B2"
        High: "\u25B2"
        High Panic: "\u25B2"
        Abnormal: "\u2666"
        Unknown: "+"
        'NA': "+"
      shapeSize: 4
      alpha: 0.6
      title: Vital signs
      label: VS

# Parameters for the 'createSubjectProfileReport' function
patientProfilesCreateReportParams:
  # export patient profiles first for subjects with AE with higher toxicity grade
  subjectSortDataFileName: adae.sas7bdat
  subjectSortVar: AESEV
  subjectSortDecreasing: TRUE
  exportBatchSize: 10 # create reports by batch of 10 patients
  timeAlignPerSubject: all

# Parameters for the table
tableParams:
  dataFileName: "adsl.xpt"
  vars: ["SEX", "RACE", "ETHNIC", "SITEID", "AGE", "TRTSDT", "ARM"]
  dataProcessing:
    - filter:
      - var: "SAFFL"
        value: "Y"
        
       