# Report-specific parameters
template: listingTemplate.Rmd
templatePackage: medicalMonitoring
reportTitle: "Concomitant medication: listing"
reportTitleLevel: 2
# Dataset of interest
dataFileName: CM.xpt
dataProcessing:
  - annotate:
    - dataset: dm
      vars: ["RFXSTDTC"] 
  - filter:
    # safety analysis set: treated-patients
    - var: "RFXSTDTC" 
      value: ""
      rev: true
# Table parameters
tableParams:
  tableVars:
    - "USUBJID"
    - "CMDECOD"
    - "CMDOSE"
    - "CMDOSU"
    - "CMROUTE"    
    - "CMCLAS"
    - "VISIT"
    - "CMSTDTC"
    - "CMSTDY"
    - "CMENDTC"
    - "CMENDY"
    - "CMINDC"
